[build]
target = "x86_64-pc-windows-gnu"

[env]
PKG_CONFIG_PATH = "C:/msys64/ucrt64/lib/pkgconfig"

[target.x86_64-pc-windows-gnu]
linker = "C:/msys64/ucrt64/bin/gcc.exe"
ar     = "C:/msys64/ucrt64/bin/ar.exe"
